var rawdata = 
[
"wie","comme","as","toy ny",
"ich","je","I","aho",
"seine","son","his","ny",
"dass","que","that","fa",
"er","il","he","izy",
"für","pour","for","fa",
"auf","sur","on","amin’ny",
"sind","sont","are","dia",
"mit","avec","with","amin’ny",
"sie","ils","they","izy ireo",
"sein","être","be","ho",
"bei","à","at","amin’ny",
"ein","un","one","iray",
"haben","avoir","have","manana",
"dies","ce","this","izany",
"durch","par","by","amin’ny",
"heiß","chaud","hot","mafana",
"Wort","mot","word","teny",
"aber","mais","but","fa",
"was","que","what","inona",
"einige","certains","some","ny sasany",
"ist","est","is","dia",
"es","il","it","izany",
"Du","tu","you","ianao",
"oder","ou","or","na",
"hatte","eu","had","nanana",
"die","la","the","ny",
"von","de","of","ny",
"zu","à","to","ny",
"und","et","and","ary",
"ein","un","a","ny",
"bei","dans","in","amin’ny",
"wir","nous","we","izahay",
"können","pouvoir","can","afaka",
"aus","dehors","out","avy",
"andere","autre","other","hafa",
"waren","étaient","were","ireo",
"die","qui","which","izay",
"tun","faire","do","atao",
"ihre","leur","their","ny",
"Zeit","temps","time","fotoana",
"wenn","si","if","raha",
"werden","volonté","will","ho",
"wie","comment","how","ahoana",
"sagte","dit","said","nanao hoe:",
"ein","un","an","iray",
"jeder","chaque","each","tsirairay",
"sagen","dire","tell","milaza",
"tut","ne","does","no",
"Satz","ensemble","set","napetraka",
"wollen","vouloir","want","te",
"Luft","air","air","rivotra",
"gut","bien","well","tsara",
"auch","aussi","also","koa",
"spielen","jouer","play","milalao",
"klein","petit","small","kely",
"Ende","fin","end","tapitra",
"setzen","mettre","put","mametraka",
"Zuhause","maison","home","an-trano",
"lesen","lire","read","vakio",
"seits","main","hand","tanana",
"Hafen","port","port","seranan-tsambo",
"groß","grand","large","lehibe",
"buchstabieren","épeler","spell","tsipelina",
"hinzufügen","ajouter","add","ampio",
"auch","même","even","na dia",
"Lande","terre","land","tany",
"hier","ici","here","eto",
"muss","il faut","must","tsy maintsy",
"groß","grand","big","lehibe",
"hoch","haut","high","avo",
"so","tel","such","toy izany",
"folgen","suivre","follow","manaraka",
"Akt","acte","act","zavatra",
"warum","pourquoi","why","antony",
"fragen","interroger","ask","manontany",
"Männer","hommes","men","ny olona",
"Veränderung","changement","change","fanovana",
"ging","est allé","went","nandeha",
"Licht","lumière","light","fahazavana",
"Art","genre","kind","tsara fanahy",
"aus","de","off","eny",
"müssen","besoin","need","mila",
"Haus","maison","house","trano",
"Bild","image","picture","sary",
"versuchen","essayer","try","manandrana",
"uns","nous","us","antsika",
"wieder","encore","again","indray",
"Tier","animal","animal","biby",
"Punkt","point","point","hevitra",
"Mutter","mère","mother","ny reniny",
"Welt","monde","world","izao tontolo izao",
"in der Nähe von","près de","near","akaiky",
"bauen","construire","build","hanorina",
"selbst","soi","self","tena",
"Erde","terre","earth","eto an-tany",
"Vater","père","father","ray",
"jeder","tout","any","rehetra",
"neu","nouveau","new","vaovao",
"Arbeit","travail","work","asa",
"Teil","partie","part","Fizarana",
"nehmen","prendre","take","handray",
"erhalten","obtenir","get","mahazo",
"Ort","lieu","place","toerana",
"gemacht","fabriqué","made","nanao",
"leben","vivre","live","velona",
"wo","où","where","izay",
"nach","après","after","rehefa",
"zurück","arrière","back","indray",
"wenig","peu","little","kely",
"nur","seulement","only","ihany",
"Mann","homme","man","ny olona",
"Jahr","année","year","taona",
"kam","est venu","came","tonga",
"zeigen","montrer","show","fampisehoana",
"jeder","tous","every","rehetra",
"gut","bon","good","tsara",
"mir","moi","me","ahy",
"geben","donner","give","manome",
"unsere","notre","our","ny",
"unter","sous","under","eo ambany",
"Name","nom","name","anarana",
"sehr","très","very","tena",
"nur","juste","just","fotsiny",
"Formular","forme","form","endrika",
"Satz","phrase","sentence","didim-pitsarana",
"groß","grand","great","lehibe",
"denken","penser","think","mieritreritra",
"sagen","dire","say","milaza",
"Hilfe","aider","help","vonjeo",
"niedrig","faible","low","ambany",
"Linie","ligne","line","tsipika",
"abweichen","différer","differ","mitovy",
"wiederum","tour","turn","indray",
"Ursache","la cause","cause","antony",
"viel","beaucoup","much","be",
"bedeuten","signifier","mean","hoe",
"vor","avant","before","talohan’ny",
"Recht","droit","right","marina",
"Junge","garçon","boy","zazalahy",
"alt","vieux","old","taloha",
"zu","trop","too","koa",
"gleich","même","same","toy izany koa",
"sie","elle","she","izy",
"alle","tous","all","rehetra",
"da","là","there","ery",
"wenn","quand","when","rahoviana",
"nach oben","jusqu’à","up","ny",
"Verwendung","utiliser","use","fampiasana",
"Ihre","votre","your","ny",
"über","sur","about","ny",
"viele","beaucoup","many","maro",
"dann","puis","then","avy eo",
"sie","les","them","azy ireo",
"schreiben","écrire","write","manoratra",
"würde","voudrais","would","te",
"wie","comme","like","toy ny",
"so","si","so","izany",
"diese","ces","these","ireo",
"sie","son","her","azy",
"lange","long","long","ela",
"machen","faire","make","manao",
"Sache","chose","thing","zavatra",
"sehen","voir","see","jereo",
"ihm","lui","him","azy",
"hat","a","has","manana",
"suchen","regarder","look","mijery",
"mehr","plus","more","bebe kokoa",
"Tag","jour","day","andro",
"könnte","pourrait","could","afaka",
"gehen","aller","go","mandeha",
"kommen","venir","come","ho avy",
"tat","fait","did","nanao",
"Anzahl","nombre","number","isa",
"klingen","son","sound","feo",
"nicht","aucun","no","tsy",
"am meisten","plus","most","indrindra",
"Menschen","personnes","people","ny olona",
"wissen","savoir","know","mahafantatra",
"Wasser","eau","water","rano",
"als","que","than","noho ny",
"Anruf","appel","call","antso",
"erste","première","first","voalohany",
"die","qui","who","izay",
"können","peut","may","mety",
"nach unten","vers le bas","down","midina",
"Seite","côté","side","lafiny",
"gewesen","été","been","efa",
"jetzt","maintenant","now","ankehitriny",
"finden","trouver","find","hahita",
"Kopf","tête","head","lohany",
"stehen","supporter","stand","mitsangana",
"besitzen","propre","own","manokana",
"Seite","page","page","pejy",
"sollte","devrait","should","tokony",
"Land","pays","country","firenena",
"gefunden","trouvé","found","hita",
"Antwort","réponse","answer","valiny",
"Schule","école","school","am-pianarana",
"wachsen","croître","grow","mitombo",
"Studie","étude","study","fianarana",
"noch","encore","still","mbola",
"lernen","apprendre","learn","mianatra",
"Anlage","usine","plant","fototra",
"Abdeckung","couvercle","cover","fonony",
"Lebensmittel","nourriture","food","sakafo",
"Sonne","soleil","sun","masoandro",
"zwischen","entre","between","eo",
"Zustand","état","state","fanjakana",
"halten","garder","keep","foana",
"Auge","œil","eye","maso",
"nie","jamais","never","na oviana na oviana",
"letzte","dernier","last","farany",
"lassen","laisser","let","aoka",
"Gedanken","pensée","thought","nihevitra",
"Stadt","ville","city","tanàna",
"Baum","arbre","tree","hazo",
"überqueren","traverser","cross","miampita",
"Bauernhof","ferme","farm","toeram-pambolena",
"Beginn","début","start","nanomboka",
"Macht","puissance","might","mety",
"Geschichte","histoire","story","tantara",
"Säge","scie","saw","tsofa",
"weit","loin","far","lavitra",
"Meer","mer","sea","ranomasina",
"ziehen","tirer","draw","hanatona",
"links","gauche","left","niala",
"spät","tard","late","tara",
"laufen","courir","run","Run",
"unterlassen Sie","needs a context","don’t","aza",
"während","tandis que","while","raha",
"Presse","presse","press","mpanao gazety",
"Schließen","proche","close","akaiky",
"Nacht","nuit","night","alina",
"Leben","vie","life","fiainana",
"wenige","peu","few","vitsivitsy",
"Norden","nord","north","avaratra",
"Buch","livre","book","boky",
"tragen","porter","carry","mitondra",
"nahm","a pris","took","naka",
"Wissenschaft","science","science","ny siansa",
"essen","manger","eat","mihinana",
"Zimmer","chambre","room","efitra",
"Freund","ami","friend","namana",
"begann","a commencé","began","nanomboka",
"Idee","idée","idea","hevitra",
"Fisch","poisson","fish","trondro",
"berg","montagne","mountain","tendrombohitra",
"Stopp","Arrêtez","stop","mijanòna",
"einmal","une fois","once","indray mandeha",
"Basis","base","base","fototra",
"hören","entendre","hear","mihainoa",
"Pferd","cheval","horse","soavaly",
"Schnitt","coupe","cut","notapatapahina",
"sicher","sûr","sure","azo antoka",
"beobachten","regarder","watch","mijery",
"Farbe","couleur","color","loko",
"Gesicht","face","face","endrika",
"Holz","bois","wood","hazo",
"Haupt-","principal","main","lehibe",
"geöffnet","ouvert","open","misokatra",
"scheinen","paraître","seem","toa",
"zusammen","ensemble","together","miara-",
"nächste","suivant","next","manaraka",
"weiß","blanc","white","fotsy",
"Kinder","enfants","children","ankizy",
"Start","commencer","begin","manomboka",
"bekam","eu","got","nahazo",
"gehen","marcher","walk","mandeha",
"Beispiel","exemple","example","ohatra",
"erleichtern","facilité","ease","hanamaivana",
"Papier","papier","paper","taratasy",
"Gruppe","groupe","group","vondrona",
"immer","toujours","always","foana",
"Musik","musique","music","mozika",
"diejenigen","ceux","those","ireo",
"beide","tous les deux","both","samy",
"Marke","marque","mark","marika",
"oft","souvent","often","matetika",
"Schreiben","lettre","letter","taratasy",
"bis","jusqu’à ce que","until","mandra-",
"Meile","mile","mile","kilaometatra",
"Fluss","rivière","river","ony",
"Auto","voiture","car","fiara",
"Füße","pieds","feet","tongotra",
"Pflege","soins","care","fikarakarana",
"zweite","deuxième","second","faharoa",
"genug","assez","enough","ampy",
"Ebene","plaine","plain","tani-hay",
"Mädchen","fille","girl","ankizivavy",
"üblich","habituel","usual","mahazatra",
"jung","jeune","young","tanora",
"bereit","prêt","ready","vonona",
"oben","au-dessus","above","ambony",
"je","jamais","ever","mandrakizay",
"rot","rouge","red","mena",
"Liste","liste","list","lisitra",
"obwohl","bien que","though","aza",
"fühlen","sentir","feel","mahatsapa",
"Vortrag","parler","talk","lahateny",
"Vogel","oiseau","bird","vorona",
"bald","bientôt","soon","tsy ho ela",
"Körper","corps","body","vatana",
"Hund","chien","dog","amboa",
"Familie","famille","family","fianakaviana",
"direkt","direct","direct","mivantana",
"Pose","pose","pose","mametraka",
"verlassen","laisser","leave","miala",
"Lied","chanson","song","hira",
"messen","mesurer","measure","mandrefy",
"Tür","porte","door","varavarana",
"Produkt","produit","product","vokatra",
"schwarz","noir","black","mainty",
"kurz","court","short","fohy",
"Zahl","chiffre","numeral","Anarana iombonana",
"Klasse","classe","class","am-pianarana",
"Wind","vent","wind","rivotra",
"Frage","question","question","fanontaniana",
"passieren","arriver","happen","hitranga",
"vollständig","complète","complete","tanteraka",
"Schiff","navire","ship","sambo",
"Bereich","zone","area","faritra",
"Hälfte","moitié","half","antsasany",
"Stein","rock","rock","vato",
"bestellen","ordre","order","mba",
"Feuer","feu","fire","afo",
"Süden","sud","south","Atsimo",
"Problem","problème","problem","olana",
"Stück","pièce","piece","kely",
"sagte","dit","told","nilaza",
"wusste","savait","knew","nahalala",
"passieren","passer","pass","nitranga",
"seit","depuis","since","satria",
"obere","haut","top","ambony",
"ganze","ensemble","whole","rehetra",
"König","roi","king","mpanjaka",
"Straße","rue","street","teny an-dalana",
"Zoll","pouce","inch","mirefy",
"multiplizieren","multiplier","multiply","hahamaro",
"nichts","rien","nothing","na inona na inona",
"Kurs","cours","course","Mazava ho azy fa",
"bleiben","rester","stay","mijanona",
"Rad","roue","wheel","kodiarana",
"voll","plein","full","feno",
"Kraft","force","force","hery",
"blau","bleu","blue","manga",
"Objekt","objet","object","zavatra",
"entscheiden","décider","decide","manapa-kevitra",
"Oberfläche","surface","surface","ambonin’ny",
"tief","profond","deep","lalina",
"Mond","lune","moon","volana",
"Insel","île","island","nosy",
"Fuß","pied","foot","tongotra",
"System","système","system","rafitra",
"beschäftigt","occupé","busy","be asa",
"Prüfung","test","test","fitsapana",
"Rekord","record","record","rakitsoratra",
"Boot","bateau","boat","sambokely",
"gemeinsam","commun","common","iombonana",
"goldenen","or","gold","volamena",
"möglich","possible","possible","azo atao",
"Flugzeug","plan","plane","fiaramanidina",
"statt","place","stead","hisolo",
"trocken","sec","dry","maina",
"Wunder","se demander","wonder","manontany tena",
"Lachen","rire","laugh","nihomehy mihitsy",
"tausend","mille","thousand","arivo",
"vor","il ya","ago","lasa izay",
"lief","ran","ran","nihazakazaka",
"überprüfen","vérifier","check","hanamarina",
"Spiel","jeu","game","lalao",
"Form","forme","shape","endrika",
"gleichsetzen","assimiler","equate","equate",
"heiß","chaud","hot","mafana",
"Fehl","manquer","miss","Miss",
"gebracht","apporté","brought","nitondra",
"Wärme","chaleur","heat","hafanana",
"Schnee","neige","snow","oram-panala",
"Reifen","pneu","tire","kodiarana",
"bringen","apporter","bring","mitondra",
"ja","oui","yes","eny",
"entfernt","lointain","distant","lavitra",
"füllen","remplir","fill","mameno",
"Osten","est","east","atsinanana",
"malen","peindre","paint","nandoko",
"Sprache","langue","language","fiteny",
"unter","entre","among","eo",
"Einheit","unité","unit","vondrona",
"Macht","puissance","power","fahefana",
"Stadt","ville","town","tanàna",
"fein","fin","fine","tsara dia tsara",
"sicher","certain","certain","sasany",
"fliegen","voler","fly","manidina",
"fallen","tomber","fall","lavo",
"führen","conduire","lead","mitarika",
"Schrei","cri","cry","fitarainany",
"dunkel","sombre","dark","maizina",
"Maschine","machine","machine","milina",
"note","Note","note","fanamarihana",
"warten","patienter","wait","miandry",
"Plan","plan","plan","drafitra",
"Abbildung","figure","figure","endrika",
"Stern","étoile","star","kintana",
"Kasten","boîte","box","boaty",
"Nomen","nom","noun","anarana iombonana",
"Feld","domaine","field","an-tsaha",
"Rest","reste","rest","fitsaharana",
"richtig","correct","correct","marina",
"fähig","capable","able","afaka",
"Pfund","livre","pound","Pound",
"getan","Terminé","done","nanaovanareo",
"Schönheit","beauté","beauty","hatsaran-tarehy",
"Antriebs","entraînement","drive","fiara",
"stand","résisté","stood","nitsangana",
"enthalten","contenir","contain","dia ahitana",
"Front","avant","front","anoloana",
"lehren","enseigner","teach","mampianatra",
"Woche","semaine","week","herinandro",
"Finale","finale","final","farany",
"gab","donné","gave","nanome",
"grün","vert","green","maitso",
"oh","oh","oh","ô",
"schnell","rapide","quick","haingana",
"entwickeln","développer","develop","hampitombo",
"Ozean","océan","ocean","ranomasina",
"warme","chaud","warm","mafana",
"kostenlos","gratuit","free","maimaim-poana",
"Minute","minute","minute","minitra",
"stark","fort","strong","mahery",
"besondere","spécial","special","manokana",
"Geist","esprit","mind","an-tsaina",
"hinter","derrière","behind","aoriana",
"klar","clair","clear","mazava",
"Schwanz","queue","tail","rambo",
"produzieren","produire","produce","voka-pambolena sy fiompiana",
"Tatsache","fait","fact","Raha ny marina",
"Raum","espace","space","toerana",
"gehört","entendu","heard","nandre",
"beste","meilleur","best","tsara indrindra",
"Stunde","heure","hour","ora",
"besser","mieux","better","tsara kokoa",
"WAHR","vrai","true","marina",
"während","pendant","during","mandritra",
"hundert","cent","hundred","jato",
"fünf","cinq","five","dimy",
"merken","rappeler","remember","tsarovy",
"Schritt","étape","step","dingana",
"früh","tôt","early","tany am-boalohany",
"halten","tenir","hold","mihazona",
"Westen","ouest","west","andrefana",
"Boden","sol","ground","tany",
"Interesse","intérêt","interest","mahaliana",
"erreichen","atteindre","reach","hahatratra",
"schnell","rapide","fast","fifadian-kanina",
"Verbum","verbe","verb","ny matoanteny amin’ny",
"singen","chanter","sing","mihira",
"hören","écouter","listen","mihaino",
"sechs","six","six","enina",
"Tabelle","table","table","latabatra",
"Reise","Voyage","travel","Tsangatsangana",
"weniger","moins","less","kely kokoa",
"Morgen","matin","morning","maraina",
"zehn","dix","ten","folo",
"einfach","simple","simple","tsotra",
"mehrere","plusieurs","several","maro",
"Vokal","voyelle","vowel","zanatsoratra",
"auf","vers","toward","amin’ny",
"Krieg","guerre","war","ady",
"legen","poser","lay","mametraka",
"gegen","contre","against","manohitra",
"Muster","modèle","pattern","fomba",
"schleppend","lent","slow","miadana",
"Zentrum","centre","center","afovoany",
"Liebe","amour","love","fitiavana",
"Person","personne","person","olona",
"Geld","argent","money","vola",
"dienen","servir","serve","manompo",
"erscheinen","apparaître","appear","hita",
"Straße","route","road","lalana",
"Karte","carte","map","sarintany",
"regen","pluie","rain","orana",
"Regel","règle","rule","fitsipika",
"regieren","gouverner","govern","hitantana",
"ziehen","tirer","pull","sintony",
"Kälte","froid","cold","mangatsiaka",
"Hinweis","avis","notice","filazana",
"Stimme","voix","voice","feo",
"Energie","énergie","energy","hery",
"Jagd","chasse","hunt","mihaza",
"wahrscheinlich","probable","probable","inoana",
"Bett","lit","bed","fandriana",
"Bruder","frère","brother","rahalahy",
"Ei","œuf","egg","atody",
"Fahrt","tour","ride","mitaingina",
"Zelle","cellule","cell","efitra",
"glauben","croire","believe","mino",
"vielleicht","peut-être","perhaps","angamba",
"pflücken","choisir","pick","haka",
"plötzlich","soudain","sudden","tampoka",
"zählen","compter","count","manisa",
"Platz","carré","square","kianja",
"Grund","raison","reason","antony",
"Dauer","longueur","length","lavany",
"vertreten","représenter","represent","maneho",
"Kunst","art","art","zava-kanto",
"Thema","sujet","subject","foto-kevitra",
"Region","région","region","faritra",
"Größe","taille","size","habeny",
"variieren","varier","vary","Tsy mitovy",
"regeln","régler","settle","hanorim-ponenana",
"sprechen","parler","speak","miteny",
"Gewicht","poids","weight","lanja",
"allgemein","général","general","ankapobeny",
"Eis","glace","ice","ranomandry",
"Materie","question","matter","zavatra",
"Kreis","cercle","circle","faribolana",
"Paar","paire","pair","mpivady",
"umfassen","inclure","include","Anisan’ny",
"Kluft","fracture","divide","fisarahana",
"Silbe","syllabe","syllable","vanin",
"Filz","feutre","felt","nahatsapa",
"groß","grandiose","grand","lehibe",
"Kugel","balle","ball","baolina",
"noch","encore","yet","nefa",
"Welle","vague","wave","alon",
"fallen","tomber","drop","mitete",
"Herz","cœur","heart","fo",
"Uhr","h","am","aho",
"vorhanden","présent","present","ankehitriny",
"schwer","lourd","heavy","mavesatra",
"Tanz","danse","dance","dihy",
"Motor","moteur","engine","maotera",
"Position","position","position","toerana",
"Arm","bras","arm","sandry",
"breit","large","wide","malalaka",
"Segel","voile","sail","niondrana an-tsambo",
"Material","matériel","material","fitaovana",
"Fraktion","fraction","fraction","ampahany",
"Wald","forêt","forest","ala",
"sitzen","s’asseoir","sit","mipetraka",
"Rennen","course","race","hazakazaka",
"Fenster","fenêtre","window","varavarankely",
"Speicher","magasin","store","fivarotana",
"Sommer","été","summer","fahavaratra",
"Zug","train","train","fiaran-dalamby",
"Schlaf","sommeil","sleep","torimaso",
"beweisen","prouver","prove","manaporofo",
"einsam","seul","lone","irery",
"Bein","jambe","leg","tongotra",
"Übung","exercice","exercise","fanatanjahan-tena",
"Wand","mur","wall","rindrina",
"Fang","capture","catch","trondro",
"Berg","monture","mount","tendrombohitra",
"wünschen","souhaiter","wish","maniry",
"Himmel","ciel","sky","lanitra",
"Board","conseil","board","birao",
"Freude","joie","joy","fifaliana",
"Winter","hiver","winter","ririnina",
"sa","sat","sat","Sat",
"geschrieben","écrit","written","voasoratra",
"wilden","sauvage","wild","bibidia",
"Instrument","instrument","instrument","fitaovana",
"gehalten","conservé","kept","foana",
"Glas","verre","glass","fitaratra",
"Gras","herbe","grass","ny ahitra",
"Kuh","vache","cow","omby vavy",
"Arbeit","emploi","job","asa",
"Rand","bord","edge","sisin’ny",
"Zeichen","signe","sign","famantarana",
"Besuch","visite","visit","fitsidihana",
"Vergangenheit","passé","past","Ny lasa",
"weich","doux","soft","malefaka",
"Spaß","amusement","fun","mahafinaritra",
"hell","clair","bright","mamirapiratra",
"Gases","gaz","gas","mandatsa-dranomaso",
"Wetter","temps","weather","toetrandro",
"Monat","mois","month","volana",
"Million","million","million","tapitrisa",
"tragen","porter","bear","Mijoro ho",
"Finish","finition","finish","farany",
"glücklich","heureux","happy","sambatra",
"hoffen","espoir","hope","manantena",
"blume","fleur","flower","voninkazo",
"kleiden","vêtir","clothe","mitafy",
"seltsam","étrange","strange","hafahafa",
"Vorbei","disparu","gone","lasa",
"Handel","commerce","trade","varotra",
"Melodie","mélodie","melody","hira fiderana",
"Reise","voyage","trip","saran-dalana",
"Büro","bureau","office","birao",
"empfangen","recevoir","receive","mandray",
"Reihe","rangée","row","ny laharana",
"Mund","bouche","mouth","vava",
"genau","exact","exact","marina",
"Zeichen","symbole","symbol","famantarana",
"sterben","mourir","die","faty",
"am wenigsten","moins","least","kely indrindra",
"Ärger","difficulté","trouble","olana",
"Schrei","cri","shout","Manaova feo fifaliana",
"außer","sauf","except","afa-tsy",
"schrieb","écrit","wrote","nanoratra",
"Samen","semence","seed","voa",
"Ton","ton","tone","fiteny",
"beitreten","joindre","join","hiaraka",
"vorschlagen","suggérer","suggest","hevitra",
"sauber","propre","clean","madio",
"Pause","pause","break","fiatoana",
"Dame","dame","lady","vehivavy",
"Hof","cour","yard","tokontany",
"steigen","augmenter","rise","mitsangana",
"schlecht","mauvais","bad","ratsy",
"Schlag","coup","blow","namely",
"Öl","huile","oil","menaka",
"Blut","sang","blood","ra",
"berühren","toucher","touch","mikasika",
"wuchs","a augmenté","grew","nitombo",
"Cent","cent","cent","#BEZUG!",
"mischen","mélanger","mix","afangaro",
"Mannschaft","équipe","team","ekipa",
"Draht","fil","wire","tariby",
"Kosten","coût","cost","vidin’ny",
"verloren","perdu","lost","very",
"braun","brun","brown","Brown",
"tragen","porter","wear","mitondra",
"Garten","jardin","garden","zaridaina",
"gleich","égal","equal","mitovy",
"gesendet","expédié","sent","naniraka",
"wählen","choisir","choose","misafidy",
"fiel","est tombé","fell","latsaka",
"passen","s’adapter","fit","antonona",
"fließen","débit","flow","mikoriana",
"Messe","juste","fair","ara-drariny",
"Bank","banque","bank","banky",
"sammeln","recueillir","collect","hanangona",
"sparen","sauver","save","afa-",
"Kontrolle","contrôle","control","fanaraha-maso",
"dezimal","décimal","decimal","decimal",
"Ohr","oreille","ear","sofina",
"sonst","autre","else","hafa",
"ganz","tout à fait","quite","tena",
"pleite","cassé","broke","namaky",
"Fall","cas","case","tranga",
"Mitte","milieu","middle","afovoany",
"töten","tuer","kill","mamono",
"Sohn","fils","son","zazalahy",
"See","lac","lake","farihy",
"Moment","moment","moment","fotoana",
"Maßstab","échelle","scale","ambaratonga",
"laut","fort","loud","mafy",
"Frühling","printemps","spring","lohataona",
"beobachten","observer","observe","mandinika",
"Kind","enfant","child","ankizy",
"gerade","droit","straight","mahitsy",
"Konsonant","consonne","consonant","consonant",
"Nation","nation","nation","firenena",
"Wörterbuch","dictionnaire","dictionary","rakibolana",
"milch","lait","milk","ronono",
"Geschwindigkeit","vitesse","speed","hafainganam-pandeha",
"Verfahren","méthode","method","fomba",
"Orgel","organe","organ","taova",
"zahlen","payer","pay","vola",
"Alter","âge","age","taona",
"Abschnitt","section","section","faritra",
"Kleid","robe","dress","fitafiana",
"Wolke","nuage","cloud","rahona",
"Überraschung","surprise","surprise","tsy nampoizina",
"ruhig","calme","quiet","mangina",
"Stein","pierre","stone","vato",
"winzig","minuscule","tiny","kely",
"Aufstieg","montée","climb","fihanihana",
"kühlen","frais","cool","milay",
"Entwurf","conception","design","famolavolana",
"arm","pauvres","poor","mahantra",
"Menge","lot","lot","be dia be",
"Versuch","expérience","experiment","andrana",
"Boden","bas","bottom","ambany",
"Schlüssel","clé","key","fototra",
"Eisen","fer","iron","vy",
"Einzel","unique","single","tokan-tena",
"Stick","bâton","stick","tapa-kazo",
"Wohnung","plat","flat","marin-",
"zwanzig","vingt","twenty","roa-polo",
"Haut","peau","skin","hoditra",
"Lächeln","sourire","smile","tsiky",
"Falte","pli","crease","crease",
"Loch","trou","hole","lavaka",
"springen","sauter","jump","hitsambikina",
"Kind","bébé","baby","Baby",
"acht","huit","eight","valo",
"Dorf","village","village","tanàna",
"treffen","se rencontrent","meet","mivory",
"Wurzel","racine","root","faka",
"kaufen","acheter","buy","mividy",
"erhöhen","augmenter","raise","atsangano",
"lösen","résoudre","solve","mamaha",
"Metall","métal","metal","metaly",
"ob","si","whether","na",
"drücken","pousser","push","atoseho",
"sieben","sept","seven","fito",
"Absatz","paragraphe","paragraph","andinin-tsoratra",
"dritte","troisième","third","fahatelo",
"wird","doit","shall","dia",
"Hand","en attente","held","Held",
"Haar","cheveux","hair","volony",
"beschreiben","décrire","describe","mamaritra",
"Koch","cuisinier","cook","Cook",
"Boden","étage","floor","rihana",
"entweder","chaque","either","na",
"Ergebnis","résultat","result","vokatra",
"brennen","brûler","burn","hodorana",
"Hügel","colline","hill","colina",
"sicher","coffre-fort","safe","azo antoka",
"Katze","chat","cat","saka",
"Jahrhundert","siècle","century","taonjato",
"betrachten","envisager","consider","Diniho",
"Typ","type","type","karazany",
"Gesetz","droit","law","lalàna",
"Bit","peu","bit","kely",
"Küste","côte","coast","fari-",
"Kopie","copie","copy","dika mitovy",
"Ausdruck","phrase","phrase","andian-teny",
"still","silencieux","silent","mangina",
"hoch","haut","tall","lava",
"Sand","sable","sand","fasika",
"Boden","sol","soil","nofon-tany",
"Rolle","rouleau","roll","horonam-boky",
"Temperatur","température","temperature","mari-pana",
"Finger","doigt","finger","rantsan-tànany",
"Industrie","industrie","industry","orinasa",
"Wert","valeur","value","danja",
"Kampf","lutte","fight","ady",
"Lüge","mensonge","lie","lainga",
"schlagen","battre","beat","nandresy",
"begeistern","exciter","excite","manaitaitra",
"natürlich","naturel","natural","voajanahary",
"Blick","vue","view","View",
"Sinn","sens","sense","hevitra",
"Hauptstadt","capital","capital","Renivohitra",
"wird nicht","ne sera pas","won’t","dia tsy",
"Stuhl","chaise","chair","seza",
"Achtung","danger","danger","loza",
"Obst","fruit","fruit","vokatra",
"reich","riche","rich","manan-karena",
"dick","épais","thick","matevina",
"Soldat","soldat","soldier","miaramila",
"Prozess","processus","process","dingana",
"betreiben","fonctionner","operate","miasa",
"Praxis","pratique","practice","fanao",
"trennen","séparé","separate","misaraka",
"schwierig","difficile","difficult","sarotra",
"Arzt","médecin","doctor","dokotera",
"Bitte","s’il vous plaît","please","mba miangavy re",
"schützen","protéger","protect","miaro",
"Mittag","midi","noon","mitataovovonana",
"Ernte","récolte","crop","vokatra",
"modernen","moderne","modern","ankehitriny",
"Elementes","élément","element","singa",
"treffen","frapper","hit","voa",
"Schüler","étudiant","student","mpianatra",
"Ecke","coin","corner","zoro",
"Partei","partie","party","antoko",
"Versorgung","alimentation","supply","famatsiana",
"deren","dont","whose","izay",
"lokalisieren","localiser","locate","toerana",
"Rings","anneau","ring","peratra",
"Charakter","caractère","character","toetra",
"insekt","insecte","insect","bibikely",
"gefangen","pris","caught","tratra",
"Zeit","période","period","fotoana",
"zeigen","indiquer","indicate","maneho",
"Funk","radio","radio","onjam-peo",
"Speiche","rayon","spoke","niteny",
"Atom","atome","atom","tsivaky",
"Mensch","humain","human","olombelona",
"Geschichte","histoire","history","tantara",
"Wirkung","effet","effect","vokatry",
"elektrisch","électrique","electric","elektrika",
"erwarten","attendre","expect","manantena",
"Knochen","os","bone","taolana",
"Schiene","rail","rail","lalamby",
"vorstellen","imaginer","imagine","sary an-tsaina",
"bieten","fournir","provide","manome",
"zustimmen","se mettre d’accord","agree","miombon-kevitra",
"so","ainsi","thus","dia toy izany no",
"sanft","doux","gentle","malemy fanahy",
"Frau","femme","woman","vehivavy",
"Kapitän","capitaine","captain","komandin’ny",
"erraten","deviner","guess","maminavina",
"erforderlich","nécessaire","necessary","ilaina",
"scharf","net","sharp","maranitra",
"Flügel","aile","wing","elatra",
"schaffen","créer","create","hamorona",
"Nachbar","voisin","neighbor","mpiara-belona",
"Wasch","lavage","wash","Wash",
"Fledermaus","chauve-souris","bat","ramanavy",
"eher","plutôt","rather","fa",
"Menge","foule","crowd","vahoaka",
"mais","blé","corn","katsaka",
"vergleichen","comparer","compare","ampitahao amin’ny",
"Gedicht","poème","poem","tononkalo",
"Schnur","chaîne","string","kofehy",
"Glocke","cloche","bell","Bell",
"abhängen","dépendre","depend","miankina",
"Fleisch","viande","meat","hena",
"einreiben","rub","rub","RUB",
"Rohr","tube","tube","fantsona",
"berühmt","célèbre","famous","malaza",
"Dollar","dollar","dollar","dolara",
"Strom","courant","stream","Stream",
"Angst","peur","fear","tahotra",
"Blick","vue","sight","fahitana",
"dünn","mince","thin","manify",
"Dreieck","triangle","triangle","telozoro",
"Erde","planète","planet","planeta",
"Eile","se dépêcher","hurry","faingana",
"Chef","chef","chief","lehiben’ny",
"Kolonie","colonie","colony","zanatany",
"Uhr","horloge","clock","famantaranandro",
"Mine","mine","mine","ny ahy",
"Krawatte","lien","tie","karavato",
"eingeben","entrer","enter","hiditra",
"Dur","majeur","major","lehibe",
"frisch","frais","fresh","vaovao",
"Suche","recherche","search","fikarohana",
"senden","envoyer","send","handefa",
"gelb","jaune","yellow","mavo",
"Pistole","pistolet","gun","basy",
"erlauben","permettre","allow","hamela",
"Druck","impression","print","printy",
"tot","mort","dead","maty",
"Stelle","place","spot","toerana",
"Wüste","désert","desert","efitra",
"Anzug","costume","suit","niantso ny Fiangonany",
"Strom","courant","current","amin’izao fotoana izao",
"Aufzug","ascenseur","lift","atraka",
"stiegen","rose","rose","nitsangana",
"ankommen","arriver","arrive","tonga",
"Stamm","maître","master","tompony",
"Spur","piste","track","lalana",
"Elternteil","mère","parent","ray aman-dreny",
"Ufer","rivage","shore","eny an-tanety",
"Teilung","division","division","fizarana",
"Blatt","feuille","sheet","lamba",
"Substanz","substance","substance","fananana",
"begünstigen","favoriser","favor","mankasitraka",
"verbinden","relier","connect","mifandray",
"nach","poste","post","lahatsoratra",
"verbringen","passer","spend","mandany",
"Akkord","corde","chord","chord",
"Fett","graisse","fat","tavy",
"froh","heureux","glad","faly",
"Original","original","original","tany am-boalohany",
"Aktie","part","share","anjara",
"Station","station","station","peo",
"Papa","papa","dad","Dada",
"Brot","pain","bread","mofo",
"aufladen","charger","charge","Mampianiana",
"richtig","propre","proper","iombonana",
"Leiste","bar","bar","bar",
"Angebot","proposition","offer","tolotra",
"Segment","segment","segment","ampahany",
"Sklave","esclave","slave","mpanompo",
"ente","canard","duck","gana",
"Augenblick","instant","instant","avy hatrany",
"Markt","marché","market","tsena",
"Grad","degré","degree","diplaoma",
"besiedeln","peupler","populate","hameno",
"küken","poussin","chick","zana-borona",
"liebe","cher","dear","malala",
"Feind","ennemi","enemy","fahavalo",
"antworten","répondre","reply","navalin’i",
"Getränk","boisson","drink","zava-pisotro",
"auftreten","se produire","occur","mitranga",
"Unterstützung","support","support","fanohanana",
"Rede","discours","speech","miteny",
"Natur","nature","nature","toetra",
"Angebot","gamme","range","isan-karazany",
"Dampf","vapeur","steam","etona",
"Bewegung","mouvement","motion","Soratra Masina",
"Weg","chemin","path","lalana",
"Flüssigkeit","liquide","liquid","rano",
"protokollieren","enregistrer","log","midira",
"gemeint","signifiait","meant","natao",
"Quotient","quotient","quotient","quotient",
"Gebiss","dents","teeth","nify",
"Schale","coquille","shell","akorandriaka",
"Hals","cou","neck","tendany",
"Sauerstoff","oxygène","oxygen","ôksizenina",
"Zucker","sucre","sugar","siramamy",
"Tod","décès","death","fahafatesana",
"ziemlich","assez","pretty","tsara tarehy",
"Geschicklichkeit","compétence","skill","fahaiza-manao",
"Frauen","femmes","women","vehivavy",
"Saison","saison","season","vanim-potoana",
"Lösung","solution","solution","vahaolana",
"Magnet","aimant","magnet","andriamby",
"Silber","argent","silver","volafotsy",
"danken","merci","thank","misaotra",
"Zweig","branche","branch","sampana",
"Spiel","rencontre","match","lalao",
"Suffix","suffixe","suffix","suffix",
"insbesondere","particulièrement","especially","indrindra",
"Feige","figue","fig","aviavy",
"ängstlich","peur","afraid","raiki-tahotra",
"riesig","énorme","huge","goavana",
"Schwester","sœur","sister","rahavavy",
"Stahl","acier","steel","vy",
"diskutieren","discuter","discuss","hevitra",
"vorwärts","avant","forward","handroso",
"ähnlich","similaire","similar","mitovy",
"führen","guider","guide","hitari-dalana",
"Erfahrung","expérience","experience","traikefa",
"Partitur","score","score","maty",
"apfel","pomme","apple","paoma",
"gekauft","acheté","bought","nividy",
"geführt","LED","led","led",
"Tonhöhe","pas","pitch","dity",
"Mantel","manteau","coat","akanjo",
"Masse","masse","mass","faobe",
"Karte","carte","card","karatra",
"Band","bande","band","tarika",
"Seil","corde","rope","tady",
"Rutsch","glissement","slip","taratasy mi-",
"gewinnen","gagner","win","Win",
"träumen","rêver","dream","manonofy",
"Abend","soirée","evening","hariva",
"Zustand","condition","condition","toe-",
"Futtermittel","alimentation","feed","fahana",
"Werkzeug","outil","tool","fitaovana",
"gesamt","total","total","tanteraka",
"Basis","de base","basic","fototra",
"Geruch","odeur","smell","manimbolo",
"Tal","vallée","valley","dohasaha",
"noch","ni","nor","na",
"doppelt","double","double","avo roa heny",
"Sitz","siège","seat","seza",
"fortsetzen","continuer","continue","foana",
"Block","bloc","block","andian-tsoratra",
"Tabelle","graphique","chart","tabilao",
"Hut","chapeau","hat","satroka",
"verkaufen","vendre","sell","mivarotra",
"Erfolg","succès","success","fahombiazana",
"Firma","entreprise","company","orinasa",
"subtrahieren","soustraire","subtract","analana",
"Veranstaltung","événement","event","zava-nitranga",
"besondere","particulier","particular","manokana",
"viel","accord","deal","fifanarahana",
"schwimmen","baignade","swim","milomano",
"Begriff","terme","term","teny",
"Gegenteil","opposé","opposite","mifanohitra",
"Frau","femme","wife","vadiny",
"Schuh","chaussure","shoe","kiraro",
"Schulter","épaule","shoulder","soroka",
"Verbreitung","propagation","spread","fielezan’ny",
"arrangieren","organiser","arrange","handamina",
"Lager","camp","camp","toby",
"erfinden","inventer","invent","mamorona",
"Baumwolle","coton","cotton","landihazo",
"geboren","né","born","Born",
"bestimmen","déterminer","determine","mamaritra",
"Quart","litre","quart","litatra",
"neun","neuf","nine","sivy",
"Lastwagen","camion","truck","kamiao",
"Lärm","bruit","noise","feo",
"Ebene","niveau","level","ambaratonga",
"Chance","chance","chance","kisendrasendra",
"sammeln","recueillir","gather","hanangona",
"Geschäft","boutique","shop","fivarotana",
"Stretch","tronçon","stretch","mihinjitra",
"werfen","jeter","throw","hitora",
"Glanz","éclat","shine","hamirapiratra",
"Immobilien","propriété","property","fananana",
"Spalte","colonne","column","tsanganana",
"Molekül","molécule","molecule","molekiola",
"wählen","sélectionner","select","mifidy",
"FALSCH","mal","wrong","diso",
"grau","gris","gray","volondavenona",
"Wiederholung","répétition","repeat","Avereno",
"erfordern","exiger","require","mitaky",
"breit","large","broad","malalaka",
"vorbereiten","préparer","prepare","hiomana",
"Salz","sel","salt","sira",
"Nase","nez","nose","orona",
"mehreren","pluriel","plural","teny",
"Zorn","colère","anger","fahatezerana",
"Anspruch","revendication","claim","fitarainana",
"Kontinent","continent","continent","kaontinanta"
]

var newList = [];

for (var i = 0; i < rawdata.length; i+=4) {
	var de = rawdata[i];
	var fr = rawdata[i+1];
	var en = rawdata[i+2];
	var mg = rawdata[i+3];
	
	var listNr = Math.floor(i / 60);
	if (!newList[listNr]) {
		newList[listNr] = {name : {de : "Wörter " + listNr, en: "Words " + listNr, fr: "Mots " + listNr, mg : "Teny " + listNr}, de : [], en : [], fr : [], mg : []};
	}
	newList[listNr].en.push(en);
	newList[listNr].mg.push(mg);
	newList[listNr].fr.push(fr);
	newList[listNr].de.push(de);
	
	
}
console.log(JSON.stringify(newList));
