var words = {
"abidy" : "Alphabet", 
"adala" : "Verrückter/verrückt",
"adidy" : "Pflicht",
"adino" : "vergessen",
"adiresy" : "Adresse",
adrisa: Heuschrecke,
ady : Kampf/Striet/Krieg,
afa-po: zufrieden/nicht mehr weiter wissen,
afatsy:außer,
afaka:bestehen/können/frei,
afakomaly:vorgestern,
afo:Feuer,
afokasoka:Streichholz,
afovoany:(in der) Mitte,
aho:ich,
ahoana:wie,
ahy:mein/mir/mich,
aiza:wo,
akaiky:nah,
akanjo:Kleidung,
akany:Heimat/Nest,
akoho:Huhn,
akondro:Banane,
akorandriaka:Muschel,
ala:Wald,
ala-olana:Lösung,
alahady:Sonntag,
alahelo:Traurigkeit,
alakamisy:Donnerstag,
alalana:Erlaubnis,
alarobia:Mittwoch,
alatsaka:fallen lassen/absetzen,
alatsinainy:Montag,
alema: deutsch,
aleo:lieber,
alika:Hund,
alina: Nacht/zehntausend,
aloa:bezahlt werden,
aloha:zunächst/vor,
aloka:Schatten,
amana:und,
ambadika:hinter,
ambany:unter,
ambin'ny:und(Zahl),
ambiny:übrig,
ambony:über/hoch/auf,
amby:Rest,
amin'izay: auf diese Weise,
amin'ny:zum/um,
aminao:mit dir,
aminay:mit uns,
aminy:mit ihm,
amoron-drano-masina:am Strand,
amaron-tsiraka ampahafiriny: an der Küste,
ampahafiriny:wieviel (in Bruchzahl),
ampahany:Bruchzahl,
amponga:Trommel,
ampy:ausreichend,
anabavy: Schwester (eines Manns),
anadahy: Bruder (einer Frau),
an-dafy:im Ausland,
anao:dich/dir/dein,
anaram-bositra:Spitzname,
anarana:Name,
anareo:euer,
anaty:in,
anay:unser,
andao:Lasst uns (...),
andray:(Ausruf der Überraschung),
andriamatoa:erster Sohn/Herr,
andro:Tag,
androany:heute,
androngo:Echse,
anefa:aber/hingegen,
angaha:(Fragepartikel),
angamba:vielleicht,
angano:Märchen/Unglücksfall,
anglisy:englisch,
anie:doch,
anio:heute,
an'iza:wessen,
anjely:Engel,
ankehitriny:heutzutage,
ankihibe:Daumen,
ankihikely:kleiner Finger,
ankizilahy:Junge,
ankizivavy:Mädchen,
ankizy:Kind/die anderen,
anoloana:gegenüber/vorn,
antoka:Garantie,
antitra:alt,
antoandro:am Tag/am Vormittag,
antoniny:mittelmäßig,
antonona:passend
antsasany:die Hälfte,
antsika:uns/unser,
antsy:Messer,
any:dort,
ao:dort,
aogositra:August,
aoka:Lass das!,
aoriana:hinten/nach,
aotra:null,
arabe:Straße,
arabo:Araber,
arahaba:Gruß,
aretina:Krankheit,
arivo:Tausend,
ary:dort,
asa:Arbeit,
asabotsy:Samstag,
ato:hier drin,
atoandro:Mittag,
atody:Ei,
atsimo:Süd,
atsinanana:Ost,
atsy:dort,
aty:hier (hin),
avokoa:alle,
avy:kommen/zurückkommen,
avy eo:anschließend,
ay:ach so,
aza:(Ausdruck des Verbots),
azafady:Entschuldigung,
azo:verstanden/erhalten,
azoazo:mäßig,
azy:ihn/sein/ihr,
baiboly:Bibel,
baiko:Befehl,
baolina:Ball,
basivava:geschwätzig,
be:viel/groß,
bebe:ziemlich viel/Oma,
betsaka:zahlreich,
biby:Tier,
bie:Ticket,
bika:Körperbau,
birao:Büro,
bisikilety:Fahrrad,
boaty:Dose,
boky:Buch,
borosy:Bürste,
bota:dick,
dada:Papa,
dadabe:Opa,
dadatoa:ältester Onkel,
daholo:alle,
dahalo:Gauner,
dia:und/dann/Spur/wild,
dibera:Butter,
dieny:solange,
dihy:Tanz,
diso:falsch/Fehler/schuldig,
dite:Tee,
divay:Wein,
dokotera:Arzt,
doma:dumm,
dozenina:Dutzend,
efa:vollendet/schon,
efitra:Zimmer/Wüste,
efitrano:Zimmer,
ekena:akzeptiert,
ela:lange,
elaela:einige Zeit,
elanelana:Abstand,
elo:Regenschirm,
entana:Gepäck/Ware,
entina:mitnehmen,
eny:ja/dort,
eo:da,
eroa:dort,
ery:sehr/dort,
Etazonia:die Vereinigten Staaten,
eto:hier,
etsy:da,
ety:hier,
ezaka:Anstrengung
fa:aber/dass/weil,
fady:Tabu,
fahafiry:wievielte,
fahasalamana:Gesundheit,
fahavalo:Feind,
fahefana:Macht,
fahiny:damals,
fahoriana:Armut,
fakan-drivotra:Urlaub,
fakan-tsary:Fotoapparat,
fako:Müll,
faly:froh,
famangiana:Besuch,
fambolena:Landwirtschaft,
famerenana:wiederholung,
famerim-bola:Restgeld,
famonjena:Rettung,
fanadinana:Prüfung,
fanafody:Medikament,
fanaka:Möbel,
fanalahidy:Schlüssel,
fanambadiana:Ehe/Hochzeit,
fanampiana:Hilfe,
fananana:Vermögen,
fanantenana:Hoffnung,
fanasana:Einladung/Waschen,
fanazarana:Übung,
fanazavana:Erklärung,
fandriana:Bett,
fangatahana:Bitte/Antrag,
fanimpiriny:zum wievielten Mal?,
fanina:schwindlig,
faniriana:Wunsch,
fanjaitra:Nadel,
fanjakana:Staat,
fanomezana:Geschenk/Gabe,
fanondro:Zeigefinger,
fantatra:bekannt,
farafara:Bett,
farany:Ende/letzte,
faravavy:jüngste Töchter,
faritra:Gebiet,
fasika:Sand,
feno:voll,
feo:Stimme,
fepetra:Voraussetzung,
fera:Bügeleise,
fetsy:schlau,
fety:Fest,
fiainana:Leben,
fiaingana:Abfahrt,
fianakaviana:Familie,
fianarana:Studium,
fiangaviana:Bitte,
fiantsoana:Aufforderung,
fiara:Fahrzeug,
fidirana:Eintritt,
fifaliana:Freude,
fifaninanana:Wettbewerb,
fihaoanana:Begegnung,
fijaliana:Leid,
filaminana:Ordnung,
filoha:Chef,
finoana:Glaube,
firaisana:Vereinigung,
firariana:Glückwunsch,
firavana:Feierabend/Schluss,
firenena:Land,
firy:wieviel,
fisaorana:Dank,
fisarahana:Trennung/Abschied,
fitaovana:Material,
fitaratra:Spiegel,
fitiavana:Liebe,
fitsangatsanganana:Ausflug,
fitsarana:Bericht,
fitsipi-pitenenana:Grammatik,
fitsipika:Lineal/Regel,
fivarotana:Verkauf/Laden,
fivoriana:Versammlung,
fo:Herz,
fofona:Geruch,
fohy:kurz,
foibe:Zentrale,
fomba:Sitte/Art und Weise,
foana:immer/leer,
fony:als,
forsety:Gabel,
fotoan-gasy:mit Verspätung,
fotoana:Zeit/Termin,
fotsiny:nur,
fotsy:weiß,
fy:lecker,
gaga:erstaunt,
gana:Ente,
gara:Bahnhof,
gasy:Madagasse,
gazety:Zeitung,
gidro:Affe/hässlich,
gisa:Ente,
gorodana:Fußboden,
gripa:Grippe,
haavo:Hölle,
habe:Größe,
hafa:anders,
hafahafa:komisch,
hafanana:Wärme,
hafatra:Bestellung,
haingana:schnell,
haja:Respekt,
hajia:Briefmarke,
halatra:Diebstahl,
halava:Länge,
hanina:Essen/Futter,
haody ô:Darf man hereinkommen?,
harena:Reichtum,
hariva:abends,
harona:Einkaufstasche,
hatramin'ny:bis(Zeit),
hatreny:bis(Distanz),
havana:Verwandte,
havia:links,
hay:gewusst,
hazo:Baum,
hehy:Lachen,
hena:Fleisch,
hendry:brav,
henoy:Hör zu!,
herinandro:Woche,
hery:Kraft,
hetaheta:Durst,
hetsy:hunderttausend,
hety:Schere/Haarschnitt,
hevitra:Rat/Sinn,
hira:Lied,
hita:gesehen,
hoe:folgendes,
hofa:Miete,
hono:angeblich,
hoy:sagt,
ianao:du,
ianareo:ihr,
ie:ja,
ihany:ohnehin,
ikala:(Artikel),
ilaina:benötigt,
indraindray:ab und zu,
indray:wieder,
indraindra:vor allem,
inona:was,
intsony:nicht mehr,
inty:nimm!,
iny:da kommt,
io: das,
iraika:eins,
iray:eins,
ireny:da kommen,
ireroa:diese,
irery:allein,
ireto:diese,
iroa:diese,
iry:diese,
isa:Zahl,
isan'andro:täglich,
isan-karazany:unterschiedlich,
isika:wir(inklusiv),
iva:niedrig,
ivelany:außerhalb,
iza:wer,
izahay:wir(exklusiv),
izaho:ich,
izao:jetzt,
izany:das/also,
izay:das,
izy:er/sie/es,
izy ireo:sie,
jamba:blind,
jeneraly:General,
jeografia:Erdkunde,
jiro:Licht,
jolay:Juli,
ka:aber/so dass,
kabary:Rede,
kado:Geschenk/Trinkgeld,
kahie:Heft,
kajy:rechnen,
kamo:faul,
kanefa:aber,
kanjo:zufällig,
kaopy:Tasse,
kara-panondro:Personalausweis,
karama:Lohn,
karaoty:Karotte,
karatra:Karte,
karazana:Sorte,
katôlika:katholisch,
kely:klein,
kesika:Kiste,
kibo:Bauch,
kidora:Matratze,
kifafa:Besen,
kilalao:Spielzeug,
kilaometatra:Kilometer,
kilasy:Klasse,
kintana:Stern,
kiraro:Schuh,
kisoa:Schwein,
kitapo:Tasche,
kivy:entmutigt,
klasika:klassisch,
koa:auch/darum,
kodiarana:Reifen,
kofehy:Schnur,
kokoa:mehr,
kopia:Kopie,
korontana:Unordnung,
kosa:hingegen,
kristianina:christlich,
labiera:Bier,
labozia:Kerze,
lafo:teuer,
laharana:Nummer,
lahy:Mann,
lainga:Lüge,
lakana:Einbaum,
lakile:Schlüssel,
lakolosy:Glocke,
lalana:Gesetz,
lalana:Weg,
lalandava:stets,
lalantsara:Flur,
lalao:Spiel,
lamaody:Mode,
lamba:Stoff,
lanitra:Himmel,
lanja:Gewicht,
lany:aufgebraucht,
lany andro:veraltet,
laoka:Reisbeilage,
lasa:fortgegangen,
lasantsy:Benzin,
lasopy:Suppe,
latabatra:Tisch,
latsaka:gefallen/unter,
lava:lang,
lavaka:Loch,
lavitra:weit,
lavitrisa:eine Milliarde,
lehibe:groß/Chef,
lehilahy:Mann,
leitsy:(Anrede zwischen Männern),
lemaka:ebenes Land,
lena:nass,
leo:es satt haben,
lesona:Lektion,
lisitra:Liste,
litatra:Liter,
litera:Buchstabe,
lo:verfault,
loaka:Loch,
loatra:sehr,
lobaka:Hemd,
loha:Kopf,
loharano:Quelle,
lohasaha:Tal,
lohataona:Frühling,
loka:Wette,
loko:Farbe,
lolo:Schmetterling,
loto:Dreck,
lovia:Teller,
loza:Unfall,
madama:Frau,
madinika:Kleingeld/schmächtig,
madio:sauber,
maditra:trotzig,
mafana:warm,
mafy:stark,
magazay:Laden,
mahafaly:erfreulich,
mahafantatra:kennen/wissen,
mahafatifaty:niedlich,
mahafaty:tödlich,
mahafinaritra:angenehm,
mahagaga:erstaunlich,
mahakamo:langweilig,
mahalala:kennen,
mahandro:kochen,
mahantra:arm,
mahare:hören,
maharitra:dauern,
mahasoa:nützlich,
mahasosotra:ärgerlich,
mahatoky:vertrauen,
mahatonga:verursachen/bekommen,
mahatratra:erreichen,
mahatsiaro:sich erinnern/bewusst,
mahavariana:spannend/erstaunlich,
mahavita:abschließen/fähig,
mahay:intelligent/können,
mahazaka:tragen können/vertragen,
mahazatra:gewöhnlich,
mahazo:bekommen/verstehen,
mahery:kräftig,
mahery setra:brutal,
mahia:mager,
mahita:finden/sehen,
mahitsy:gerade,
mahomby:erfolgreich,
maika:eilig,
maikamaika:etwas in Eile,
maimbo:stinkend,
maina:trocken,
maintso:grün,
mainty:schwarz,
maivana:leicht,
maizina:dunkel,
maka:nehmen,
maka aina:sich ausruhen,
malabary:traditionelles Männerhemd,
malahelo:traurig,
malala:Liebling/geliebt,
malalaka:geräumig,
malama:glatt,
malaza:berühmt,
malazo:verwelkt,
malefaka:sanft,
malemy:schwach/gelähmt,
maloto:schmutzig,
mamafa:fegen/abwischen,
mamaha:aufmachen/Problem lösen,
mamahana:füttern,
mamaky:lesen/kaputt,
mamaly:antworten,
mamana:aufwärmen,
mamandrika:vorbestellen,
mamangy:besuchen,
mamantana:direkt ankommen,
mamarana:beenden,
mamatotra:binden,
mamboly:pflanzen,
mamela:erlauben,
mamelatra:ausbreiten,
mamelona:ernähren/anzünden,
mameno:füllen,
mamerina:wiederholen/zurück geben,
mametaka:aufkleben,
mametraka:hinstellen,
mamily:lenken,
mamindra:umstellen/marschieren,
mamiratra:glänzen,
mamita:vollenden,
mamitaka:betrügen,
mamo:betrunken,
mamoaka:herausbringen,
mamoha:öffnen/aufwecken,
mamokatra:produzieren,
mamonjy:retten/teilnehmen,
mamono:umbringen/einpacken,
mamony:blühen,
mamorona:erfinden,
mamory:sammeln,
mampalahelo:mitleiderregend,
mampamangy:Schöne Grüße!,
mampianatra:lehren,
mampiasa:arbeiten lassen,
mampiditra:hereinbringen/anziehen,
mampirana:aufräumen,
mampisaraka:auseinanderbringen,
mampiseho:vorführen,
mampita:weiterleiten,
mampitohy:verbinden,
mampitovy:vergleichen,
mamy:süß,
manabataba:stören,
manabe:erziehen,
manadina:befragen,
manadino:vergessen,
manadio:putzen,
manafatra:bestellen,
manafika:angreifen,
manafina:verstecken,
manahoana:Hallo,
manahy:befürchten,
manaiky:zustimmen,
manainga:aufbrechen,
manaja:respektieren,
manajanona:unterbrechen,
manakaiky:sich annähern,
manakatona:(zu)schließen,
manala:ausziehen/abrechnen,
manamafy:bestärken,
manamarika:notieren,
manamarina:nachprüfen,
manambady:heiraten/verheiratet sein,
manambaka:betrügen,
manambara:ankündigen,
manambatra:addieren,
manamboatra:herstellen/reparieren,
manampy:helfen/ergänzen,
manana:haben/reich,
manandrana:probieren,
manan-karena:wohlhabend,
manangona:sammeln,
manantena:hoffen,
manantona:zu jemanden gehen/hängen,
manao:tun,
manapaka:entscheiden/schneiden,
manaraka:der nächste,
manary:wegwerfen,
manasa:einladen/waschen,
manasoa:guttun,
manatanteraka:vollziehen,
manatitra:begleiten/wegbringen,
manatsara:verbessern,
manavy:Fieber haben,
mandainga:lügen,
mandalo:vergänglich/vorbeikommen,
mandamina:aufräumen,
mandany:Geld ausgeben,
mandefa:abschicken,
mandeha:gehen,
mandidy:schneiden/befehlen,
mandihy:tanzen,
mandimby:ablösen,
mandinika:durchdenken,
mandoa:bezahlen,
mandoko:malen,
mandondona:anklopfen,
mandositra:flüchten,
mandoto:beschmutzen,
mandra-pihaona:Bis zum nächsten Mal!,
mandrafitry:tischlern,
mandrakizay:für immer,
mandrakotra:bedecken,
mandrara:verbieten,
mandraraka:gießen/ausschütten,
mandratra:verletzen,
mandrava:abbauen/zerstören,
mandray:nehmen/empfangen,
mandrefy:ausmessen,
mandrehitra:anzünden/einschalten,
mandreraka:ermüdend,
mandresy:siegen,
manditra:während,
mandro:duschen,
mandroso:servieren/hereinkommen,
mandrosoa:Komm herein!,
mandry:liegen,
manelingelina:stören,
manenjika:verfolgen,
maneno:klingeln,
manety:schneiden,
manga:blau,
mangalatra:stehlen,
mangataka:bitten,
mangatsiaka:kalt,
mangetaheta:Durst,
mangina:still/schweigen,
manidina:fliegen,
manidy:zuschließen,
manify:dünn,
manimba:beschädigen,
maninona:was/warum,
manipy:werfen
maniry:wünschen/blühen,
manisa:zählen,
manitra:duftend,
manja:hübsch,
manjaitra:nähen,
manjaka:herrschen,
manjary:werden,
mankaiza:wohin,
mankany:hingehen,
mankaty:herbeikommen,
manko:nämlich,
manodidina:umkreisen,
manofa:mieten,
manofy:träumen,
manokatra:(er)öffnen,
manolo:ersetzen,
manolotra:überreichen,
manomana:vorbereiten,
manomboka:beginnen,
manome:geben,
manonoa:aussprechen,
manontany:fragen,
manoratra:schreiben,
manoroka:küssen,
manova:ändern,
manta:roh,
maraina:früh/morgens,
maranitra:scharf,
marary:krank,
maratra:verletzt,
mariazy:Hochzeit,
marikivy:sauer,
marina:richtig,
maro:viel,
maromaro:einige,
masaka:gekocht/reif,
masiaka:böse/streng/scharf,
masinina:Maschine/Zug,
maso:Auge,
masoandro:Sonne,
matahotra:Angst haben,
matanjaka:kräftig,
matavy:dick,
matetika:häufig,
matevina:dick/dicht,
matoky:zuversichtlich sein,
matory:schlafen,
matsiro:lecker,
maty:eingegangen/gestorben,
mavesatra:schwer,
mavo:gelb,
mavokely:rosa,
may:verbrannt/ungeduldig,
mazava:hell/klar,
mazoto:fleißig,
mba:mal (Bitte),
mbola:noch,
mena:rot,
menaka:Öl,
menatra:schüchtern,
metatra:Meter,
mety:passend/vielleicht,
miadana:glücklich/reich/langsam,
miady:sich streiten,
miaina:leben/atmen,
miainga:abfahren/abfliegen,
miakatra:einsteigen,
miala:abfahren/abfliegen,
miampy:hinzukommen,
mianadahy:Geschwister,
mianaka:(Verwandschaftsverhältnis zwischen Eltern und Kindern),
mianakavy:die ganze Familie,
mianatra:lernen/studieren,
miandry:warten,
mianjera:umfallen,
miantsena:einkaufen,
miantso:aufrufen,
miarahabe:begrüßen,
miaraka:zusammen,
miasa:arbeiten,
miborosy:bürsten,
midina:landen/heruntergehen,
miditra:mit der Arbeit anfangen,
mieritreritra:überlegen,
miezaka:sich bemühen,
mifampiarahaba:sich begrüßen,
mifanaiky:sich einigen,
mifanara-kevitra:sich einigen,
mifanena:sich begegnen,
mifankahita:sich treffen,
mifanontany:sich gegenseitig fragen,
mifanoratra:sich schreiben,
mifidy:wählen,
mihaino:(zu)hören,
mihaja:edel/elegant,
mihantona:hängen,
mihantra:Mitleid haben,
mihinana:etwas essen,
mihira:singen,
mihitsy:sogar,
mihoatra:überholen,
mihomehy:lachen,
mijanona:anhalten/zu Hause bleiben,
mijery:(an)sehen,
mikarankara:vorbereiten,
mikasa:vorhaben,
mikasika:berühren/bezüglich,
mikiakiaka:herumschreien,
mikorontana:durcheinander,
mila:brauchen,
milahatra:sich anstellen,
milalao:spielen,
milamina:geordnet,
milasy:zelten,
milaza:sagen,
milina:Maschine,
milomalo:schwimmen,
mimenomenona:meckern,
mindrana:ausleihen,
mino:glauben,
miomana:sich auf etwas vorbereiten,
miompy:züchten,
miova:sich ändern,
mipasoka:bügeln,
mipetraka:wohnen/sitzen,
mirahalahy:Geschwister (m),
mirahavavy:Geschwister (f),
mirana:freudestrahlend,
mirary:wünschen/angemessen,
mirava:Feierabend machen,
miresadresaka:sich unterhalten,
miresaka:sprechen,
misakafo:essen,
misaotra:sich bedanken,
misasa:sich waschen,
misondrotra:hinaufgehen,
misotro:trinken,
misy:vorhanden sein/geben,
mitandrina:aufpassen,
mitantara:erzählen,
mitarika:führen/schleppen,
mitazana:erblicken,
miteny:sprechen,
mitoloko:traurig herumsitzen/stöhnen,
mitondra:mitnehmen/mitbringen,
mitovy:ähnlich sein,
mitsangana:stehen,
mitsangatsangana:spaziergehen,
misiky:lächeln,
mivaly:herauskommen (Ergebnis),
mivarotra:verkaufen,
mivavaka:beten,
miverina:zurückkommen,
mividy:kaufen,
mivily:abbiegen,
mivoaka:ausgehen/aufs Klo gehen,
mivoha:geöffnet,
mivory:sich versammeln,
mivovo:bellen,
mizara:verteilen/teilen,
môdely:Modell,
mody:nach Hause gehen,
mofo:Brot,
moka:Mücke,
momba:bezüglich,
monina:wohnen,
mora:billig/einfach,
moramora:gemütlich,
mozika:Musik,
mpamboly:Bauer,
mpamily:Fahrer,
mpampianaratra:Lehrer,
mpampiasa:Arbeitgeber,
mpanadina:Prüfer,
mpandeha:Passagier,
mpandihy:Tänzer,
mpandrafitra:Tischler,
mpanety:Friseur,
mpangalatra:Dieb,
mpangataka:Bettler,
mpanjaitra:Schneider,
mpanjaka:König,
mpanofa:Mieter,
mpanoratra:Schriftsteller,
mpianatra:Student/Schüler,
mpiasa:Arbeiter,
mpikambana:Mitglied,
mpilalao:Spieler,
mpisolo:Ersatz,
mpitarika:Führer,
mpitsara:Richter,
mpivarotra:Verkäufer,
mpividy:Kunde,
mpizaha tany:Tourist,
mponina:Einwohner,
na:oder,
na .. na:entweder .. oder,
nahoana:warum,
namana:Freund,
naoty:Note,
nefa:dennoch,
nenibe:Oma,
nenifara:jüngste Tante,
nenitoa:älteste Tante,
neny:Mutter,
ngeza:riesig,
niainga hono:es war einmal,
nify:Zahn,
no:(Konjunktion),
no ho:als(Vergleich),
noana:hungrig,
noely:Weihnachten,
nofo:Fleisch,
nofy:Traum,
noho:aufgrund,
nony:als,
nosy:Insel,
novambra:November,
ny:der/die/das,
oay:(Ausruf der Überraschung),
ohatra:Beispiel/Vorbild,
ohatrinona:Wie teuer?,
oktobra:Oktober,
olana:Problem,
olom-pirenena:Staatsbürger,
olombelona:Mensch,
olon-dehibe:Erwachsene,
olona:Person/Mensch,
omaly:gestern,
omby:Rind,
ondana:Kopfkissen,
ondry:Schaf,
ony:Fluss,
ora:Uhr/Stunde,
orana:Krebs(Tier)/Regen,
orona:Nase,
oviana:wann,
ovy:Kartoffel,
paiso:Pfirsich,
paka:Ostern,
palitao:Jacke,
paoma:Apfel,
maopmy:Pumpe,
paositra:Postamt,
paradisa:Paradies,
pataloha:Hose,
pejy:Seite,
penina:Kugelschreiber,
pensily hazo:Bleistift,
peratra:Ring,
piso:Katze,
pôlisy:Polizei/Polizist,
porofo:Beweis,
poizina:Gift,
prezida:Präsedent,
ra:Blut,
raha:als/wenn/falls,
rahafakampitso:übermorgen,
rahalahy:Bruder,
rahampitso:morgen,
raharaha:Tätigkeit/Hochzeit,
rahariva:heute Abend,
rahatrizay:in Zukunft,
rahavavy:Schwester,
rahona:Wolke,
rahoviana:wann,
raibe:Großvater,
raikitra:abgemacht,
rakibolana:Wörterbuch,
ramatoa:erste Tochter/Frau,
ramose:Herr,
rangahy:Herr/Mann,
rankizy:(Anreder der Eltern zu Kindern),
rano:Wasser,
ranomasina:Meer,
ranomaso:Träne,
raozy:Rose,
ratsy:schlecht/hässlich,
rava:vernichtet/abgebaut,
ravina:Blatt,
ray:Vater,
ray aman-dreny:Eltern,
refy:Maß,
rehefa:wenn,
rehetra:alle/alles,
renibe:Grußmutter,
renirano:Fluss,
renivohitra:Hauptstadt,
reny:Mutter,
reraka:müde,
resaka:Gespräch,
resy:besigt,
rindrina:Wind,
ririnina:Winter,
rivotra:Wind/Luft,
roa:zwei,
roapolo:zwanzig,
rojo:Kette,
ronono:Milch,
rosia:Quittung,
rosianina:Russe/russisch,
rova:Palast,
rovitra:zerrissen,
sa:oder,
sady:außerdem,
sady .. no:sowohl .. als auch,
saha:Feld,
sahala:ähnlich/gleich,
sahaza:passend,
sahirana:beschäftigt/bedürftig,
saika:beinahe,
saina:Verstand/Flagge,
saingy:aber/dennoch,
saka:Katze,
sakafo:Essen,
sakaiza:Freund/Geliebter,
salady:Salat,
salama:gesund,
sambatra:glücklich,
samihafa:unterschreiben,
samy:jeder/beide,
sanatria:falls/niemals,
sao:falls/zufällig/nicht .. dass,
saosisy:Wurst,
saotra:Dank,
sarety:Karre,
sariaka:sympathisch,
saribakoly:Puppe,
sarobidy:wertvoll,
sambo:Schiff,
sarotra:kompliziert,
sary:Photo,
sasany:einige,
sasatra:müde,
satria:weil,
satroka:Hut,
savony:Seife,
sazy:Strafe,
sekoly:Schule,
sempotra:außer Atem,
sendra:zufällig,
sento:Seufzer,
seranam-piaramanidina:Flughafen,
seranana:Hafen,
servieta:Handtuch,
sery:Schnupfen,
setroka:Rauch,
seza:Stuhl,
sigara:Zigarette,
simba:beschädigt,
sinema:Kino,
sinoa:Chinese,
sira:Salz,
siramamy:Zucker,
sisa:Rest,
sisin-dalana:Fußweg,
sitrane:wieder gesund,
sivy:neun,
soa:gut,
soavaly:Pferd,
sobika:Korb,
sofina:Ohr,
sola:kahl,
solo:Ersatz,
solomaso:Brille,
sonia:Unterschrift,
soratra:Schrift,
sosoa:Frühstücksreis,
sosotra:ärgerlich,
sotro:Löffel,
spaoro:Sport,
sy:und,

};
