var words = {
"abidy" : "Alphabet", 
"adala" : "Verrückter/verrückt",
"adidy" : "Pflicht",
"adino" : "vergessen",
"adiresy" : "Adresse",
adrisa: Heuschrecke,
ady : Kampf/Striet/Krieg,
afa-po: zufrieden/nicht mehr weiter wissen,
afatsy:außer,
afaka:bestehen/können/frei,
afakomaly:vorgestern,
afo:Feuer,
afokasoka:Streichholz,
afovoany:(in der) Mitte,
aho:ich,
ahoana:wie,
ahy:mein/mir/mich,
aiza:wo,
akaiky:nah,
akanjo:Kleidung,
akany:Heimat/Nest,
akoho:Huhn,
akondro:Banane,
akorandriaka:Muschel,
ala:Wald,
ala-olana:Lösung,
alahady:Sonntag,
alahelo:Traurigkeit,
alakamisy:Donnerstag,
alalana:Erlaubnis,
alarobia:Mittwoch,
alatsaka:fallen lassen/absetzen,
alatsinainy:Montag,
alema: deutsch,
aleo:lieber,
alika:Hund,
alina: Nacht/zehntausend,
aloa:bezahlt werden,
aloha:zunächst/vor,
aloka:Schatten,
amana:und,
ambadika:hinter,
ambany:unter,
ambin'ny:und(Zahl),
ambiny:übrig,
ambony:über/hoch/auf,
amby:Rest,
amin'izay: auf diese Weise,
amin'ny:zum/um,
aminao:mit dir,
aminay:mit uns,
aminy:mit ihm,
amoron-drano-masina:am Strand,
amaron-tsiraka ampahafiriny: an der Küste,
ampahafiriny:wieviel (in Bruchzahl),
ampahany:Bruchzahl,
amponga:Trommel,
ampy:ausreichend,
anabavy: Schwester (eines Manns),
anadahy: Bruder (einer Frau),
an-dafy:im Ausland,
anao:dich/dir/dein,
anaram-bositra:Spitzname,
anarana:Name,
anareo:euer,
anaty:in,
anay:unser,
andao:Lasst uns (...),
andray:(Ausruf der Überraschung),
andriamatoa:erster Sohn/Herr,
andro:Tag,
androany:heute,
androngo:Echse,
anefa:aber/hingegen,
angaha:(Fragepartikel),
angamba:vielleicht,
angano:Märchen/Unglücksfall,
anglisy:englisch,
anie:doch,
anio:heute,
an'iza:wessen,
anjely:Engel,
ankehitriny:heutzutage,
ankihibe:Daumen,
ankihikely:kleiner Finger,
ankizilahy:Junge,
ankizivavy:Mädchen,
ankizy:Kind/die anderen,
anoloana:gegenüber/vorn,
antoka:Garantie,
antitra:alt,
antoandro:am Tag/am Vormittag,
antoniny:mittelmäßig,
antonona:passend
antsasany:die Hälfte,
antsika:uns/unser,
antsy:Messer,
any:dort,
ao:dort,
aogositra:August,
aoka:Lass das!,
aoriana:hinten/nach,
aotra:null,
arabe:Straße,
arabo:Araber,
arahaba:Gruß,
aretina:Krankheit,
arivo:Tausend,
ary:dort,
asa:Arbeit,
asabotsy:Samstag,
ato:hier drin,
atoandro:Mittag,
atody:Ei,
atsimo:Süd,
atsinanana:Ost,
atsy:dort,
aty:hier (hin),
avokoa:alle,
avy:kommen/zurückkommen,
avy eo:anschließend,
ay:ach so,
aza:(Ausdruck des Verbots),
azafady:Entschuldigung,
azo:verstanden/erhalten,
azoazo:mäßig,
azy:ihn/sein/ihr,
baiboly:Bibel,
baiko:Befehl,
baolina:Ball,
basivava:geschwätzig,
be:viel/groß,
bebe:ziemlich viel/Oma,
betsaka:zahlreich,
biby:Tier,
bie:Ticket,
bika:Körperbau,
birao:Büro,
bisikilety:Fahrrad,
boaty:Dose,
boky:Buch,
borosy:Bürste,
bota:dick,
dada:Papa,
dadabe:Opa,
dadatoa:ältester Onkel,
daholo:alle,
dahalo:Gauner,
dia:und/dann/Spur/wild,
dibera:Butter,
dieny:solange,
dihy:Tanz,
diso:falsch/Fehler/schuldig,
dite:Tee,
divay:Wein,
dokotera:Arzt,
doma:dumm,
dozenina:Dutzend,
efa:vollendet/schon,
efitra:Zimmer/Wüste,
efitrano:Zimmer,
ekena:akzeptiert,
ela:lange,
elaela:einige Zeit,
elanelana:Abstand,
elo:Regenschirm,
entana:Gepäck/Ware,
entina:mitnehmen,
eny:ja/dort,
eo:da,
eroa:dort,
ery:sehr/dort,
Etazonia:die Vereinigten Staaten,
eto:hier,
etsy:da,
ety:hier,
ezaka:Anstrengung
fa:aber/dass/weil,
fady:Tabu,
fahafiry:wievielte,
fahasalamana:Gesundheit,
fahavalo:Feind,
fahefana:Macht,
fahiny:damals,
fahoriana:Armut,
fakan-drivotra:Urlaub,
fakan-tsary:Fotoapparat,
fako:Müll,
faly:froh,
famangiana:Besuch,
fambolena:Landwirtschaft,
famerenana:wiederholung,
famerim-bola:Restgeld,
famonjena:Rettung,
fanadinana:Prüfung,
fanafody:Medikament,
fanaka:Möbel,
fanalahidy:Schlüssel,
fanambadiana:Ehe/Hochzeit,
fanampiana:Hilfe,
fananana:Vermögen,
fanantenana:Hoffnung,
fanasana:Einladung/Waschen,
fanazarana:Übung,
fanazavana:Erklärung,
fandriana:Bett,
fangatahana:Bitte/Antrag,
fanimpiriny:zum wievielten Mal?,
fanina:schwindlig,
faniriana:Wunsch,
fanjaitra:Nadel,
fanjakana:Staat,
fanomezana:Geschenk/Gabe,
fanondro:Zeigefinger,
fantatra:bekannt,
farafara:Bett,
farany:Ende/letzte,
faravavy:jüngste Töchter,
faritra:Gebiet,
fasika:Sand,
feno:voll,
feo:Stimme,
fepetra:Voraussetzung,
fera:Bügeleise,
fetsy:schlau,
fety:Fest,
fiainana:Leben,
fiaingana:Abfahrt,
fianakaviana:Familie,
fianarana:Studium,
fiangaviana:Bitte,
fiantsoana:Aufforderung,
fiara:Fahrzeug,
fidirana:Eintritt,
fifaliana:Freude,
fifaninanana:Wettbewerb,
fihaoanana:Begegnung,
fijaliana:Leid,
filaminana:Ordnung,
filoha:Chef,
finoana:Glaube,
firaisana:Vereinigung,
firariana:Glückwunsch,
firavana:Feierabend/Schluss,
firenena:Land,
firy:wieviel,
fisaorana:Dank,
fisarahana:Trennung/Abschied,
fitaovana:Material,
fitaratra:Spiegel,
fitiavana:Liebe,
fitsangatsanganana:Ausflug,
fitsarana:Bericht,
fitsipi-pitenenana:Grammatik,
fitsipika:Lineal/Regel,
fivarotana:Verkauf/Laden,
fivoriana:Versammlung,
fo:Herz,
fofona:Geruch,
fohy:kurz,
foibe:Zentrale,
fomba:Sitte/Art und Weise,
foana:immer/leer,
fony:als,
forsety:Gabel,
fotoan-gasy:mit Verspätung,
fotoana:Zeit/Termin,
fotsiny:nur,
fotsy:weiß,
fy:lecker,
gaga:erstaunt,
gana:Ente,
gara:Bahnhof,
gasy:Madagasse,
gazety:Zeitung,
gidro:Affe/hässlich,
gisa:Ente,
gorodana:Fußboden,
gripa:Grippe,
haavo:Hölle,
habe:Größe,
hafa:anders,
hafahafa:komisch,
hafanana:Wärme,
hafatra:Bestellung,
haingana:schnell,
haja:Respekt,
hajia:Briefmarke,
halatra:Diebstahl,
halava:Länge,
hanina:Essen/Futter,
haody ô:Darf man hereinkommen?,
harena:Reichtum
};
