var words = {
"abidy" : "Alphabet", 
"adala" : "Verrückter/verrückt",
"adidy" : "Pflicht",
"adino" : "vergessen",
"adiresy" : "Adresse",
adrisa: Heuschrecke,
ady : Kampf/Striet/Krieg,
afa-po: zufrieden/nicht mehr weiter wissen,
afatsy:außer,
afaka:bestehen/können/frei,
afakomaly:vorgestern,
afo:Feuer,
afokasoka:Streichholz,
afovoany:(in der) Mitte,
aho:ich,
ahoana:wie,
ahy:mein/mir/mich,
aiza:wo,
akaiky:nah,
akanjo:Kleidung,
akany:Heimat/Nest,
akoho:Huhn,
akondro:Banane,
akorandriaka:Muschel,
ala:Wald,
ala-olana:Lösung,
alahady:Sonntag,
alahelo:Traurigkeit,
alakamisy:Donnerstag,
alalana:Erlaubnis,
alarobia:Mittwoch,
alatsaka:fallen lassen/absetzen,
alatsinainy:Montag,
alema: deutsch,
aleo:lieber,
alika:Hund,
alina: Nacht/zehntausend,
aloa:bezahlt werden,
aloha:zunächst/vor,
aloka:Schatten,
amana:und,
ambadika:hinter,
ambany:unter,
ambin'ny:und(Zahl),
ambiny:übrig,
ambony:über/hoch/auf,
amby:Rest,
amin'izay: auf diese Weise,
amin'ny:zum/um,
aminao:mit dir,
aminay:mit uns,
aminy:mit ihm,
amoron-drano-masina:am Strand,
amaron-tsiraka ampahafiriny: an der Küste,
ampahafiriny:wieviel (in Bruchzahl),
ampahany:Bruchzahl,
amponga:Trommel,
ampy:ausreichend,
anabavy: Schwester (eines Manns),
anadahy: Bruder (einer Frau),
an-dafy:im Ausland,
anao:dich/dir/dein,
anaram-bositra:Spitzname,
anarana:Name,
anareo:euer,
anaty:in,
anay:unser,
andao:Lasst uns (...),
andray:(Ausruf der Überraschung),
andriamatoa:erster Sohn/Herr,
andro:Tag,
androany:heute,
androngo:Echse,
anefa:aber/hingegen,
angaha:(Fragepartikel),
angamba:vielleicht,
angano:Märchen/Unglücksfall,
anglisy:englisch,
anie:doch,
anio:heute,
an'iza:wessen,
anjely:Engel,
ankehitriny:heutzutage,
ankihibe:Daumen,
ankihikely:kleiner Finger,
ankizilahy:Junge,
ankizivavy:Mädchen,
ankizy:Kind/die anderen,
anoloana:gegenüber/vorn,
antoka:Garantie,
antitra:alt,
antoandro:am Tag/am Vormittag,
antoniny:mittelmäßig,
antonona:passend


};
